/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ImageWithBinary { 
    id?: number;
    type?: ImageWithBinary.TypeEnum;
    imageData?: Array<string>;
}
export namespace ImageWithBinary {
    export type TypeEnum = 'GENERAL' | 'THUMBNAIL';
    export const TypeEnum = {
        GENERAL: 'GENERAL' as TypeEnum,
        THUMBNAIL: 'THUMBNAIL' as TypeEnum
    };
}