/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {OrderItem} from './orderItem';

export interface Order {
  id?: number;
  userId?: number;
  status?: Order.StatusEnum;
  createdAt?: Date;
  statusLastModify?: Date;
  sumOfItems?: number;
  orderItems?: Array<OrderItem>;
}

export namespace Order {
  export type StatusEnum = 'CREATED' | 'WORKING' | 'PREPARING' | 'DELIVERING' | 'COMPLETED';
  export const StatusEnum = {
    CREATED: 'CREATED' as StatusEnum,
    WORKING: 'WORKING' as StatusEnum,
    PREPARING: 'PREPARING' as StatusEnum,
    DELIVERING: 'DELIVERING' as StatusEnum,
    COMPLETED: 'COMPLETED' as StatusEnum
  };
  export const Statuses: Array<StatusEnum> = ["CREATED", "WORKING", "PREPARING", "DELIVERING", "COMPLETED"]
}
